name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          az acr login --name myContainerRegistry
          docker build -t mycontainerregistry.azurecr.io/myapp:${{ github.sha }} .
          docker push mycontainerregistry.azurecr.io/myapp:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/aks-set-context@v2
        with:
          resource-group: myResourceGroup
          cluster-name: myAKSCluster

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/myapp myapp=mycontainerregistry.azurecr.io/myapp:${{ github.sha }}
          kubectl rollout status deployment/myapp
